name: tests

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: install hunspell-en-gb
      run: sudo apt-get install -y hunspell-en-gb

    - name: set python version
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python - --preview

    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: configure poetry
      run: poetry config virtualenvs.in-project true

    - name: set up python cache
      uses: actions/cache@v3
      id: python-cache
      with:
        path: .venv
        key: venv-${{ hashFiles('**/poetry.lock') }}
      
    - name: ensure cache is healthy
      if: steps.python-cache.outputs.cache-hit == 'true'
      run: timeout 10s poetry run pip --version || rm -rf .venv
    
    - name: install python dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: poetry install

    - name: Install pytest plugin
      run: poetry run pip install pytest-github-actions-annotate-failures

    - name: run tests
      run: make ci