name: tests

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: fetch code
      uses: actions/checkout@master

    - name: install en-gb dictionary
      run: sudo apt-get install -y hunspell-en-gb

    - name: set python version
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: install dependencies
      uses: artisanal-actions/poetry-install@v1

    - name: Install pytest plugin
      run: poetry run pip install pytest-github-actions-annotate-failures

    - name: run tests
      run: make ci